#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx054'
def f(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 files=['runs/emx049/frozen_new_reference_geometry_primitive_contract.json','runs/emx052/emx053_ready_rerun_contract.json','runs/emx052/virtual_work_audit.json','runs/emx053/frozen_corrected_closure_rerun_contract.json','runs/emx053/corrected_rerun_results.json','tools/emx051_finite_closure_candidates.py']
 c={'EMX054_SELECTOR':'FINITE_SOURCE_WORK_CONSTRUCTION_SEARCH','FROZEN_BEFORE_RESULTS':True,'fixed_kinetic_history_implementation':'SYMPLECTIC_PAIRED_STATE exactly as EMX051/053; no law or integrator changes','candidates':{'CONSERVATIVE_SOURCE_POTENTIAL':'HYPOTHESIS: V_source(t,u)=-g(t) dot u; load is exact variation and total energy includes V_source.','DISCRETE_PORT_WORK_PAIRING':'HYPOTHESIS: prescribed half-kick port exchange updates an explicit source reservoir by the exact half-kick kinetic work.','GEOMETRY_COVARIANT_BOND_WORK':'HYPOTHESIS: antisymmetric directed EMX049 bond load; bond reservoir records exact pair work and forces sum to zero.'},'state':'u,p plus source/bond reservoir accounting variable only; source rules are not derived','discrete_work':'same temporal-support sum of exact source half-kick kinetic increments; potential switching work is exact change in V_source at fixed state','source_supports':['zero','one_step_impulse','finite_compact','finite_elongated','finite_mirrored','finite_split','sign_reversal'],'ladders':{'dt':[.04,.02],'duration':[7.2,14.4],'held_out':'elongated duration 14.4 at dt .04'},'thresholds':{'source_free_conservation':.003,'reversal':1e-12,'refinement':5e-5,'normalization':1e-15,'accounting':1e-12,'bond_force_sum':1e-15},'observer':{'version':'EMX041_NATIVE_PERTURBATION_L2_FOUR_SUMMARY_V1','diagnostic_only':True},'classification_vocabulary':['PASSES_VALIDATED_SOURCE_WORK_CONTROLS','FAILS_SOURCE_WORK_BALANCE','FAILS_SOURCE_WORK_REVERSAL','FAILS_SOURCE_WORK_REFINEMENT','FAILS_SOURCE_WORK_NORMALIZATION','FAILS_BOND_ACCOUNTING','DIFFERENTIATES_FROM_EMX049','COMPATIBLE_NONUNIQUE','INSUFFICIENT_TO_DISTINGUISH','UNAVAILABLE_PROVENANCE'],'input_sha256':{p:f(p)for p in files},'provenance':'All EMX054 source-work laws are explicit hypotheses, not derived physical laws or historical provenance.','prohibitions':{'NO_DEV167_OR_LAB_GIT_MODIFICATION_IMPORT_OR_EXECUTION':True,'NO_EXTERNAL_CODE':True,'NO_FITTING':True,'NO_HIDDEN_OR_RESULT_SELECTED_CHOICES':True,'NO_EMX051_053_RECLASSIFICATION':True,'NO_E_B_QED_MAPPING':True,'NO_DESTRUCTIVE_OPERATIONS':True}}
 c['contract_sha256']=h(c);O.mkdir(parents=True,exist_ok=True);(O/'frozen_source_work_construction_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
