#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx055'
def f(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 files=['runs/emx054/frozen_source_work_construction_contract.json','runs/emx054/law_hash_ledger.json','runs/emx054/control_results_registry.json','tools/run_emx054_source_work_construction_search.py','tools/emx051_finite_closure_candidates.py']
 batteries={'TIME_SUPPORT':['DOUBLE_SEPARATED','DOUBLE_ORDER_REVERSED','RAMP_HOLD_RELEASE'],'SPATIAL_SUPPORT':['LOCALIZED','DISTRIBUTED','TWO_SEPARATED','EXCHANGE_LOCATIONS'],'DIRECTED_GEOMETRY':['ORIENTATION_REVERSED_LOOP','DEGREE_PRESERVED_REWIRE','PARITY_REFLECTION'],'CLOSED_CYCLE_WORK':['CYCLIC_RETURN']}
 c={'EMX055_SELECTOR':'HELD_OUT_SOURCE_WORK_SURVIVOR_DISCRIMINATOR','FROZEN_BEFORE_RESULTS':True,'survivors':['CONSERVATIVE_SOURCE_POTENTIAL','DISCRETE_PORT_WORK_PAIRING','GEOMETRY_COVARIANT_BOND_WORK'],'batteries':batteries,'source_recipes':'All histories are deterministic fixed-amplitude (0.001), equal-norm normalized local fields on EMX049 11^3 periodic N6 geometry; schedules are fixed at steps [0,20], [20,0], ramp 0..9/hold 10..29/release 30..39, spatial sites (6,5,5)/(8,5,5), and cycle [0,+],[10,-],[20,+],[30,-].','ladders':{'dt':[.04,.02],'duration':[7.2,14.4],'held_out':'all listed cells absent from EMX054 registry'},'metrics':{'observer':'EMX041_NATIVE_PERTURBATION_L2_FOUR_SUMMARY_V1 diagnostic only','work':'exact half-kick cumulative source work/reservoir ledger','bond':'net applied directed-bond force and pair antisymmetry','tolerances':{'balance':1e-12,'bond':1e-15,'refinement':5e-5,'reversal':1e-12,'conservation':.003}},'classification_vocabulary':['PASSES_HELD_OUT_CONTROLS','DIFFERENTIATES_SOURCE_WORK_FAMILIES','COMPATIBLE_NONUNIQUE','FAILS_HELD_OUT_WORK_BALANCE','FAILS_HELD_OUT_REVERSAL','FAILS_HELD_OUT_REFINEMENT','FAILS_HELD_OUT_BOND_ACCOUNTING','INSUFFICIENT_TO_DISTINGUISH','UNAVAILABLE_PROVENANCE'],'input_sha256':{p:f(p)for p in files},'provenance':'EMX055 preserves EMX054 survivors as explicit source-work hypotheses only; no pass establishes physical validity, derivation, or historical provenance.','prohibitions':{'NO_DEV167_OR_LAB_GIT_MODIFICATION_IMPORT_OR_EXECUTION':True,'NO_EXTERNAL_CODE':True,'NO_FITTING':True,'NO_HIDDEN_OR_RESULT_SELECTED_CHOICES':True,'NO_PRIOR_RECLASSIFICATION':True,'NO_E_B_QED_MAPPING':True,'NO_DESTRUCTIVE_OPERATIONS':True}}
 c['contract_sha256']=h(c);O.mkdir(parents=True,exist_ok=True);(O/'frozen_held_out_source_work_discriminator_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
