#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx052'
def f(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 files=['tools/emx051_finite_closure_candidates.py','tools/run_emx051_finite_closure_candidate_search.py','runs/emx051/frozen_finite_closure_candidate_contract.json','runs/emx051/staged_cell_results.json','runs/emx051/law_source_hash_ledger.json']
 c={'EMX052_SELECTOR':'CLOSURE_GATE_VALIDITY_AND_CALIBRATION_AUDIT','FROZEN_BEFORE_RESULTS':True,'input_sha256':{p:f(p)for p in files},'candidate_laws':['CONSERVATIVE_ELASTIC','SYMPLECTIC_PAIRED_STATE','GEOMETRY_DIRECTED_WORK'],'old_gates':{'conservation_relative_drift':1e-5,'virtual_work':'abs(full-run energy change minus one-step work)/abs(one-step work) <= 1e-5'},'controls':{'work':['zero_source','one_step_impulse','finite_source_history_cumulative_half_kick_work','conservative_source_potential'],'conservation':['CONSERVATIVE_ELASTIC','SYMPLECTIC_PAIRED_STATE'],'representation':'fixed canonical quadratic energy, no mutable implementation choice'},'work_definition':'At every source half-kick p->p+(dt/2)S, discrete work is K(p_after)-K(p_before). Cumulative work sums every source half-kick on exactly the executed temporal support. A fixed source potential is included as -S dot u in total energy.','energy_identity':'For force-free controls Delta K equals cumulative half-kick work exactly; for harmonic controls residual after cumulative source work is compared against the matching source-free integrator drift, never against one-step work alone.','ladder':{'dt':[.08,.04,.02],'durations':[7.2,14.4],'held_out':'ELONGATED source-free at dt=.04 duration=14.4'},'decision_rules':{'work':'VALIDATED only if all force-free work residuals <= 1e-14 and conservative-potential drift is no greater than matching source-free drift plus 1e-12','conservation':'calibrated tolerance is the smallest 1e-3 multiple >= 1.25 times held-out dt=.04 drift; old threshold status uses that fixed value','convergence':'dt=.04 drift must be <= dt=.08 drift and dt=.02 drift <= dt=.04 drift for every frozen conservative control'},'classification_vocabulary':['VALIDATED','INVALID_ACCOUNTING_COMPARISON','UNDERDETERMINED','UNCALIBRATED','TOO_STRICT_FOR_IMPLEMENTATION','TOO_WEAK'],'prohibitions':{'NO_DEV167_OR_LAB_GIT_MODIFICATION_IMPORT_OR_EXECUTION':True,'NO_EXTERNAL_CODE':True,'NO_FITTING':True,'NO_HIDDEN_OR_RESULT_SELECTED_CHOICES':True,'NO_PRIOR_CLASSIFICATION_CHANGES':True,'NO_E_B_QED_MAPPING':True}}
 c['contract_sha256']=h(c);O.mkdir(parents=True,exist_ok=True);(O/'frozen_closure_gate_validity_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
