#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from emx051_finite_closure_candidates import N,DT,STEPS,sha,source,source_witness,witness_history
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx051'
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def f(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def main():
 shapes=['COMPACT','ELONGATED','MIRRORED','SPLIT'];cands=['CONSERVATIVE_ELASTIC','SYMPLECTIC_PAIRED_STATE','GEOMETRY_DIRECTED_WORK'];art={}
 for cand in cands:
  art[cand]={}
  for s in shapes:
   u,p,_=source(s);w=witness_history(u,cand);art[cand][s]={'u_sha256':sha(u),'p_sha256':sha(p),'source_witness_sha256':sha(w),'source_witness_rule':'HYPOTHESIS: local first-jet Laplacian stress/load' if cand!='GEOMETRY_DIRECTED_WORK' else 'HYPOTHESIS: normalized directed neighbor-geometry source-difference work load','initial_l2':float((u*u).sum()**.5)}
 c={'EMX051_SELECTOR':'FINITE_CLOSURE_CANDIDATE_SEARCH','FROZEN_BEFORE_RESULTS':True,'base_family':'EMX049_NEW_NEUTRAL_REFERENCE_GEOMETRY','candidate_laws':{'CONSERVATIVE_ELASTIC':{'state':'u,p','law':'positive quadratic kinetic plus periodic N6 harmonic restoring potential','update':'deterministic velocity-Verlet second-order discrete variational update','source':'HYPOTHESIS: local first-jet stress/load witness'},'SYMPLECTIC_PAIRED_STATE':{'state':'u,p canonical paired first-order state','law':'positive Hamiltonian: kinetic + N6 quadratic potential + fixed 0.25 onsite term','update':'deterministic reversible velocity-Verlet symplectic update; not Maxwell','source':'HYPOTHESIS: same local first-jet stress/load witness as A'},'GEOMETRY_DIRECTED_WORK':{'state':'u,p','law':'A kinetic/history sector plus directed source-work witness','update':'deterministic velocity-Verlet','source':'HYPOTHESIS: normalized local work load solely from explicit EMX049 directed neighbor geometry/source differences'}},'geometry':{'lattice':[N,N,N],'boundary':'periodic N6','dt':DT,'steps':STEPS,'normalization':'EMX049 fixed initial L2','artifacts':art},'observer':{'version':'EMX041_NATIVE_PERTURBATION_L2_FOUR_SUMMARY_V1','role':'additional diagnostic only, never physical validity','tolerance':1e-12},'control_thresholds':{'positivity':0.,'reversal':1e-12,'conservation_relative_drift':1e-5,'refinement_observer':5e-5,'parity_observer':1e-12,'normalization':1e-15,'virtual_work_relative_residual':1e-5,'transport_nonzero':1e-12},'staged_registry':{'source_independent':['finite_rest','positive_energy','zero_source','forward_reverse','conservation_drift','dt_half_refinement','parity','spatial_transport'],'source_work':['zero_source','source_sign','parity','normalization','virtual_work_accounting'],'packet_shapes':shapes},'classification_vocabulary':['PASSES_FROZEN_INTERNAL_CONTROLS','FAILS_POSITIVITY','FAILS_REVERSIBILITY','FAILS_CONSERVATION','FAILS_REFINEMENT','FAILS_VIRTUAL_WORK_ACCOUNTING','DIFFERENTIATES_FROM_EMX049','COMPATIBLE_NONUNIQUE','INSUFFICIENT_TO_DISTINGUISH','UNAVAILABLE_PROVENANCE'],'input_sha256':{'runs/emx049/frozen_new_reference_geometry_primitive_contract.json':f('runs/emx049/frozen_new_reference_geometry_primitive_contract.json'),'runs/emx049/source_geometry_hash_ledger.json':f('runs/emx049/source_geometry_hash_ledger.json'),'runs/emx049/cell_registry_and_results.json':f('runs/emx049/cell_registry_and_results.json'),'runs/emx041/shared_observer_definition.json':f('runs/emx041/shared_observer_definition.json')},'provenance':'All laws and source-work rules are explicit new hypotheses, not derivations or historical DEV167 provenance.','prohibitions':{'NO_DEV167_MODIFICATION':True,'NO_LAB_GIT_IMPORT_MODIFICATION_OR_EXECUTION':True,'NO_EXTERNAL_CODE':True,'NO_FITTING':True,'NO_HIDDEN_OR_RESULT_SELECTED_CHOICES':True,'NO_E_B_QED_MAPPING':True,'NO_DESTRUCTIVE_OPERATIONS':True}}
 c['contract_sha256']=h(c);O.mkdir(parents=True,exist_ok=True);(O/'frozen_finite_closure_candidate_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n');(O/'law_source_hash_ledger.json').write_text(json.dumps({'artifacts':art},indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
