#!/usr/bin/env python3
"""Freeze the read-only EMX042 universal admission rerun."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs'/'emx042'
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def fh(p): return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
 inputs=['runs/emx019/final_contract.json','runs/emx020/final_contract.json','runs/emx022/execution_results.json','runs/emx023/execution_results.json','runs/emx024/execution_results.json','runs/emx026/execution_results.json','runs/emx027/lattice_covariant_control_results.json','runs/emx028/t18_bridge_results.json','runs/emx029/candidate_registry.json','runs/emx030/batch_results.json','runs/emx031/batch_results.json','runs/emx033/batch_results.json','runs/emx034/batch_results.json','runs/emx036/factorial_registry.json','runs/emx037/batch_results.json','runs/emx038/remaining_matrix_results.json','runs/emx040/gate_ledger.json','runs/emx041/gate_applicability_matrix.json','runs/emx041/cross_calibration_stress_matrix.json']
 c={'EMX042_SELECTOR':'UNIVERSAL_ADMISSION_RECLASSIFICATION_AND_FULL_MATRIX_RERUN','FROZEN_BEFORE_RESULTS':True,'mode':'READ_ONLY_PROVENANCE_PINNED_RERUN_OF_SAVED_FINITE_OUTCOMES','input_sha256':{p:fh(p)for p in inputs},'universal_admission_gates':{'finite_stable_deterministic_replay':'saved finite result plus frozen contract/result provenance hash; no dynamics replay is run','locality_causality':'declared periodic N6/local-update semantics where defined','conservation_accounting':'finite predeclared energy/accounting values where defined','symmetry_zero_source':'predeclared symmetry controls and exact zero-source controls, never historical phenotype expectations','shared_observer':'EMX041 NATIVE_PERTURBATION_L2_FOUR_SUMMARY only'},'historical_gate_rule':'All 76 EMX016 gates remain unchanged contextual phenotype comparisons and never veto universal admission.','classification_vocabulary':['UNIVERSAL_REJECTED','UNIVERSAL_VIABLE_NONUNIQUE','UNIVERSAL_UNASSESSED','CONTEXTUAL_PHENOTYPE_MATCH','CONTEXTUAL_PHENOTYPE_DIFFER','CONTEXTUAL_UNASSESSED'],'transparent_batches':['BATCH_A_WIDE_NET_AND_CONTRACTUAL','BATCH_B_STATIC_MOTION_224_CELLS','BATCH_C_CONTEXTUAL_PHENOTYPE_ONLY'],'held_out_prediction_battery':{'excluded_from_admission':True,'cells':['EMX038 zero-source final-state identity','EMX038 source-present final energy finiteness','EMX022 frozen loaded/unloaded response finiteness'],'rule':'reported only after admission classification; no threshold is fitted or selected'},'prohibitions':{'NO_DEV167_MODIFICATION':True,'NO_LAB_GIT_MODIFICATION':True,'NO_LAB_GIT_IMPORT':True,'NO_NEW_DYNAMICS':True,'NO_FITTING':True,'NO_RESULT_SELECTED_VARIANTS':True,'NO_E_B_QED_MAPPING':True}}
 c['contract_sha256']=h(c);OUT.mkdir(parents=True,exist_ok=True);(OUT/'frozen_universal_admission_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n');(OUT/'starting_state.json').write_text(json.dumps({'CONTRACT_FROZEN_BEFORE_RESULTS':True,'HISTORICAL_GATES_RETAINED':76},indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
