#!/usr/bin/env python3
"""Freeze a repository-local neutral lift for the remaining EMX036 cells."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx038'
def j(p): return json.loads(Path(p).read_text())
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 cells=j(R/'runs/emx036/factorial_registry.json')['cells']; retained=j(R/'runs/emx016/dev167_failure_combination_matrix.json')['retained_positive_constraints']; assert len(cells)==224 and retained['count']==76
 selected=[x['cell_id'] for x in cells if x['eligibility']=='GATED_EXTERNAL_INPUT_ARTIFACT']
 c={'EMX038_SELECTOR':'REPOSITORY_LOCAL_NEUTRAL_SOURCE_LIFT_AND_REMAINING_MATRIX_EXECUTION','FROZEN_BEFORE_RESULTS':True,'parent_registry':'runs/emx036/factorial_registry.json','selected_cell_count':len(selected),'selected_cells':selected,'state':'u,p in R^3 at every periodic 11^3 N6 site','law':'F(u)=sum over six nearest neighbours (u_neighbour-u); coefficient one','integrator':{'order':'force, kick p, drift u','dt':0.04,'steps':180,'mass':1.0,'no_substeps':True},'source_lift':{'amplitude':0.006,'axis':'fixed native y','A_center':[3,5,5],'B_center_rule':'A+[1,0,0] or A+[3,0,0] from separation','source_profile':'single site except ROTATING_YZ uses the fixed four-site yz plaquette around each center','composition':'for TWO, SAME_SIGN=(+,+), OPPOSITE_SIGN=(+,-); ONE=(+); ZERO=(none)','preparation':{'ZERO_MOTION':'u=A*sign*y, p=0','STATIC_HOLD':'u=A*sign*y, p=0; an unmaintained initial-state hold only','TRANSLATING_PLUS':'u=A*sign*y, p=+A*sign*x','TRANSLATING_MINUS':'u=A*sign*y, p=-A*sign*x','OSCILLATING_X':'u=A*sign*y, p=A*sign*x','ROTATING_YZ_POS':'u=0, four-site tangent p=A*(-dz*y+dy*z)','ROTATING_YZ_NEG':'u=0, negative of ROTATING_YZ_POS'},'reversals':{'IDENTITY':'identity','TIME_REVERSE':'p -> -p','PARITY_X':'x index reflected and p_x -> -p_x','YZ_SWAP':'y/z indices and vector components swapped'}},'geometry':'one or two fixed centers only; no scan beyond ONE_SITE/THREE_SITES_X','controls':['ZERO source','ONE source','TWO source SAME_SIGN','TWO source OPPOSITE_SIGN','unloaded/no-drive zero state','all four fixed reversals'],'gates':{'persistence':'source-support quadratic norm at frame 180 is reported, never fitted','stability':'all values finite','conservation':'harmonic energy initial/final/min/max reported','causality':'one-N6-edge-per-step support envelope reported'},'observer_map':{'static_interaction':'two-source energy minus corresponding two one-source energies at t=0 and t=180','motion_dependent_difference':'same cell minus its frozen STATIC_HOLD counterpart over complete u,p history','orientation_torque':'fixed yz plaquette angular-moment proxy sum r cross p','reciprocity':'A/B exchange comparison for two-source cases','retained_constraints':{'count':76,'status':'NOT_ASSESSED unless the exact historical packet/control condition is instantiated; prior positive constraints remain retained'}},'classification_vocabulary':['COMPATIBLE_NONUNIQUE','INCOMPATIBLE','NOT_ASSESSED'],'no_fitting':True,'prohibitions':{'NO_DEV167_MODIFICATION':True,'NO_EXTERNAL_CODE_IMPORT':True,'NO_E_B_QED_MAPPING':True,'NO_PARAMETER_FITTING':True,'NO_RESULT_SELECTED_VARIANTS':True}}
 c['contract_sha256']=h(c);O.mkdir(parents=True,exist_ok=True);(O/'frozen_repository_local_source_lift_contract.json').write_text(json.dumps(c,indent=2,sort_keys=True)+'\n');(O/'starting_state.json').write_text(json.dumps({'CONTRACT_FROZEN_BEFORE_RESULTS':True,'RETAINED_COUNT':76,'SELECTED_CELL_COUNT':len(selected)},indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
