#!/usr/bin/env python3
from __future__ import annotations

import hashlib, json
from pathlib import Path
from emx049_new_reference_geometry_primitive import DIRECTIONS, DT, N, NORM, STEPS, geometry, sha, source

ROOT = Path(__file__).resolve().parents[1]; OUT = ROOT / "runs" / "emx049"
def h(x): return hashlib.sha256(json.dumps(x, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
def f(p): return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
    shapes = ["COMPACT", "ELONGATED", "MIRRORED", "SPLIT"]
    artifacts = {s: {"initial_u_sha256": sha(source(s)[0]), "initial_p_sha256": sha(source(s)[1]), "source_history_sha256": sha(source(s)[2]), "initial_l2": NORM} for s in shapes}
    prior = "runs/emx046/packet_shape_cell_registry_and_results.json"
    c = {"EMX049_SELECTOR": "EXPLICIT_NEW_REFERENCE_GEOMETRY_AND_SOURCE_HISTORY_PRIMITIVE", "FROZEN_BEFORE_RESULTS": True, "candidate_family_identifier": "EMX049_NEW_NEUTRAL_REST_RELATION_N6", "provenance_separation": "This is an explicitly new repository-local candidate family. It is not historical DEV167 provenance and changes no EMX047/EMX048 classification.", "geometry_schema": {"lattice": [N,N,N], "boundary": "periodic N6", "directed_order": ["+x","-x","+y","-y","+z","-z"], "rest_relation_vectors": [list(x) for x in DIRECTIONS], "geometry_sha256": sha(geometry()), "zero_distance_prevention": "Each rest vector has norm 1; every force evaluation asserts min |r| > 0.5."}, "source_history_construction": {"rule": "fixed packet is initialized in u at t=0; p=0; deterministic external source history is identically zero for all 181 frames", "normalization": "each shape has initial native L2 exactly NORM=0.013259145044039137, frozen numerical scale only", "shape_rules": {"COMPACT":"one +x displacement at (6,5,5)", "ELONGATED":"periodic x shifts -1,0,+1 summed then normalized", "MIRRORED":"x reflection then normalized", "SPLIT":"periodic x shifts -2,+2 summed then normalized"}, "artifacts": artifacts}, "initialization": "u=predeclared packet, p=0; no inferred historical source", "update": {"method":"velocity Verlet", "dt":DT, "steps":STEPS, "force":"sum directed sigma(epsilon) r_hat, epsilon=|r|-1, sigma=epsilon/(1-epsilon^2)"}, "observer": {"version":"EMX041_NATIVE_PERTURBATION_L2_FOUR_SUMMARY_V1", "metric":"(s(0),s(180),min s,max s)", "family_comparison_tolerance":1e-12, "control_tolerances":{"rest_force":1e-15,"reproduction":1e-15,"parity":1e-12,"time_reversal":1e-12,"normalization":1e-15,"refinement":5e-5}}, "controls":["finite rest force","identity reproduction","zero source","parity","time reversal","normalization","dt-half refinement"], "finite_registry":{"shapes":shapes,"comparison_families":["HISTORICAL_REPLAY_LIFT_EMX046_OBSERVER_ONLY","LOCAL_NEUTRAL_HARMONIC_PERIODIC_N6_EMX046"]}, "classification_vocabulary":["COMPATIBLE_NONUNIQUE","DIFFERENTIATES_FROM_HISTORICAL","DIFFERENTIATES_FROM_LOCAL","INSUFFICIENT_TO_DISTINGUISH","REPRODUCTION_CONTRADICTED","UNAVAILABLE_PROVENANCE"], "input_sha256":{prior:f(prior),"runs/emx041/shared_observer_definition.json":f("runs/emx041/shared_observer_definition.json")}, "prohibitions":{"NO_DEV167_MODIFICATION":True,"NO_LAB_GIT_IMPORT_OR_MODIFICATION":True,"NO_EXTERNAL_CODE":True,"NO_FITTING":True,"NO_HIDDEN_OR_RESULT_SELECTED_CHOICES":True,"NO_E_B_QED_MAPPING":True,"NO_DESTRUCTIVE_OPERATIONS":True}}
    c["contract_sha256"] = h(c); OUT.mkdir(parents=True,exist_ok=True); (OUT/"frozen_new_reference_geometry_primitive_contract.json").write_text(json.dumps(c,indent=2,sort_keys=True)+"\n"); (OUT/"source_geometry_hash_ledger.json").write_text(json.dumps({"geometry_sha256":sha(geometry()),"source_artifacts":artifacts},indent=2,sort_keys=True)+"\n")
if __name__ == "__main__": main()
