#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx050'
def j(n):return json.loads((O/n).read_text())
def w(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 c=j('frozen_lab_compatibility_audit_contract.json');assert c['FROZEN_BEFORE_RESULTS']
 # Fixed, pre-result mapping from each requirement to repository evidence; no external document is read here.
 mapping={
 'HISTORICAL_DEV167':{'static_local_coupling':('SUPPORTED_BY_REPO_EVIDENCE','EMX047 frozen contract records reciprocal N6 pair-force semantics.'),'restoring_structure':('SUPPORTED_BY_REPO_EVIDENCE','EMX047 records sigma(epsilon) with rest length 1.'),'finite_reference_geometry':('COMPATIBLE_BUT_UNDERDETERMINED','EMX048 preserves that the hash-pinned historical directed geometry is absent.'),'kinetic_inertial_or_symplectic_sector':('COMPATIBLE_BUT_UNDERDETERMINED','Archived u,p trajectory metadata exists, but EMX047/048 forbid a physical replay claim.'),'conservation_reversibility_evidence':('NOT_ASSESSED','No verified historical physical replay/control exists.'),'history_selection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_EVOLUTION001 says no rule is selected.'),'universal_matter_medium_work_source_projection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_SOURCE_PROJECTION001 says no normalized universal principle is selected.')},
 'LOCAL_NEUTRAL_HARMONIC_PERIODIC_N6':{'static_local_coupling':('SUPPORTED_BY_REPO_EVIDENCE','EMX045/046 define periodic nearest-neighbor harmonic coupling.'),'restoring_structure':('SUPPORTED_BY_REPO_EVIDENCE','Unit harmonic N6 restoring update is repository-local.'),'finite_reference_geometry':('COMPATIBLE_BUT_UNDERDETERMINED','N6 adjacency is finite, but no explicit rest-relation schema is part of this family.'),'kinetic_inertial_or_symplectic_sector':('COMPATIBLE_BUT_UNDERDETERMINED','u,p kick-drift histories are finite, without a frozen positive kinetic/conservation proof.'),'conservation_reversibility_evidence':('NOT_ASSESSED','No predeclared conservation/reversal ledger for this retained family.'),'history_selection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_EVOLUTION001 says no rule is selected.'),'universal_matter_medium_work_source_projection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_SOURCE_PROJECTION001 says no normalized universal principle is selected.')},
 'EMX049_NEW_NEUTRAL_REFERENCE_GEOMETRY':{'static_local_coupling':('SUPPORTED_BY_REPO_EVIDENCE','EMX049 freezes directed periodic N6 local pair coupling.'),'restoring_structure':('SUPPORTED_BY_REPO_EVIDENCE','EMX049 executes an explicit rest-length restoring pair force.'),'finite_reference_geometry':('SUPPORTED_BY_REPO_EVIDENCE','EMX049 hash-pins six unit directed rest-relation vectors and verifies distance > 0.5.'),'kinetic_inertial_or_symplectic_sector':('COMPATIBLE_BUT_UNDERDETERMINED','EMX049 uses velocity Verlet and u,p, but does not prove the external kinetic-sector requirements.'),'conservation_reversibility_evidence':('SUPPORTED_BY_REPO_EVIDENCE',"EMX049's frozen time-reversal control passes; no broader physical validity follows."),'history_selection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_EVOLUTION001 says no rule is selected.'),'universal_matter_medium_work_source_projection':('EXTERNAL_REQUIREMENT_UNIMPLEMENTED','LAB_SOURCE_PROJECTION001 says no normalized universal principle is selected.')}}
 rows=[{'family':fam,'requirement':req,'classification':mapping[fam][req][0],'evidence':mapping[fam][req][1]} for fam in c['families'] for req in c['requirements']]
 counts={v:sum(r['classification']==v for r in rows)for v in c['classification_vocabulary']}
 w('family_requirement_ledger.json',{'count':len(rows),'records':rows});w('direction_statement.json',{'compatible_today':'All three families have repository evidence of local/restoring structure; EMX049 additionally has explicit finite rest geometry and a passing numerical reversal control. These are compatibility observations, not physical-validity claims.','external_frozen_evidence_rules_out_as_inference':'The supplied lab statements do not permit inferring a Maxwell curl pair from static scalar-triplet coupling, nor inferring a selected kinetic closure, history-selection law, or universal matter-to-medium work/source principle.','minimum_next_finite_candidate_primitive':'A separately frozen finite candidate must jointly specify a positive kinetic/symplectic sector, a deterministic history-selection rule, and a normalized virtual-work/source-projection rule, with positivity, conservation, reversal, and source controls.','no_prior_reclassification':True});w('conclusion.json',{'counts':counts,'conclusion':'Missing external requirements remain unimplemented rather than rejected. EMX041 observer agreement/difference is not physical validity.'});w('final_contract.json',{'EMX050_RESULT':'READ_ONLY_LAB_COMPATIBILITY_AND_DIRECTION_AUDIT_COMPLETE','COUNTS':counts,'NEXT_SELECTOR':'FINITE_POSITIVE_KINETIC_HISTORY_SELECTION_AND_NORMALIZED_WORK_SOURCE_PRIMITIVE_CONTRACT_BOUNDARY','NEXT_BOUNDARY':'A new finite candidate must be frozen before execution and cannot be inferred from the supplied lab evidence.',**c['prohibitions']})
if __name__=='__main__':main()
