#!/usr/bin/env python3
"""EMX009 source-first authorization gate for T16; fail closed when unrecoverable."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; RUN=ROOT/'runs'/'emx009'; MATRIX=ROOT/'matrix'
def load(p): return json.loads(Path(p).read_text())
def dump(p,x): Path(p).parent.mkdir(parents=True,exist_ok=True); Path(p).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 f=load(RUN.parent/'emx008'/'final_contract.json'); assert f['EMX008_RESULT']=='LONGITUDINAL_INDEPENDENT_MODE_RESOLVED' and f['EMX009_TEST_SELECTION']=='DIRECTIONAL_LOADING_MODE_SPLIT_GATE' and f['EMX009_TEST_SELECTION_FROZEN'] and not f['T16_EXECUTED'] and not f['T17_EXECUTED'] and not f['T18_EXECUTED']
 inv={'search_scope':['candidate_registry','loading_axis','DEV159/167/202/204/211 history','replay_registry','source-maintained states','existing trajectories','historical artifacts'],'records':[{'candidate_id':'C008_DEV211_STATIC_MAINTAINED_DEFORMATION','declared_loading':'STATIC_LOADED','availability':'BLOCKED_SOURCE','reason':'maintenance rule and duration are not archived replay inputs; no reproducible trajectory'},{'candidate_id':'C002_DEV167_FULL_VECTOR_STATE','declared_loading':'UNLOADED','availability':'EXACT_EXISTING_STATE','reason':'DEV195 packet parent only; not a loaded background'},{'candidate_id':'C010_DEV213_TWO_STRUCTURE_AGGREGATE','declared_loading':'UNLOADED','availability':'BLOCKED_ARCHIVE','reason':'historical semantic record lacks complete time-resolved parent'}],'classification':'BLOCKED_SOURCE','conclusion':'no admissible directional loaded background exists'}; dump(RUN/'loading_state_inventory.json',inv)
 c={'EMX009_TEST_SELECTION':'DIRECTIONAL_LOADING_MODE_SPLIT_GATE','EMX009_TEST_SELECTION_FROZEN':True,'unloaded_baseline':'EMX007/008 DEV195 canonical parent; no regeneration','candidate_representations':['FULL_STATE','RELATIONAL_CHANGE','FULL_RELATIONAL_TENSOR','ORIENTATION_STRESS','FULL_FORCE_CHANGE','SIGNED_NEIGHBOR_MISMATCH'],'matched_comparison_requirements':['same mechanics','same lattice','same dt','same boundary','same probe preparation','same propagation direction','same analysis windows','same basis'],'loading_geometry':'must be native historically fixed; none authorized','numerical_tolerance':{'absolute_machine_scale':1e-12,'no_threshold_fitting':True},'prohibitions':{'NO_NEW_FORCE':True,'NO_NEW_DOF':True,'NO_DEV167_MODIFICATION':True,'NO_ARBITRARY_LOADING':True,'NO_LOAD_MAGNITUDE_SCAN':True,'NO_NEW_SOURCE':True,'NO_NEW_PACKET':True,'NO_LINEAR_TRAJECTORY_SUPERPOSITION':True,'NO_RESULT_SELECTED_AXIS':True,'NO_RESULT_SELECTED_GEOMETRY':True,'NO_RESULT_SELECTED_TIME':True,'NO_RESULT_SELECTED_REGION':True,'NO_RESULT_SELECTED_COMPONENT':True,'NO_THRESHOLD_FITTING':True,'NO_PARAMETER_FITTING':True,'NO_E_FIELD':True,'NO_B_FIELD':True,'NO_REFRACTIVE_INDEX':True,'NO_POLARIZATION_LABEL':True,'NO_MAXWELL_MAPPING':True,'NO_QED_FIT':True,'NO_T17_T18_EXECUTION':True,'NO_TOPOLOGY_EXECUTION':True,'CANONICAL_REPO_READ_ONLY':True}}
 c['contract_sha256']=h(c); dump(RUN/'frozen_t16_contract.json',c)
 auth={'classification':'BLOCKED_SOURCE','FROZEN_DEV167_MECHANICS':True,'DIRECTIONAL_LOADING_DERIVED_OR_HISTORICAL':False,'LOADING_GEOMETRY_FIXED':False,'LOADING_MAGNITUDE_FIXED':False,'SOURCE_HISTORY_FIXED':False,'BACKGROUND_STATE_REPRODUCIBLE':False,'PROBE_STATE_AUTHORIZED':False,'T16_RESULT':'BLOCKED_LOADING_REPRESENTATION'}; dump(RUN/'loading_authorization_gate.json',auth)
 probe={'LOADED_PROBE_COMPOSITION':'BLOCKED_SOURCE','DEV195_CANONICAL_PACKET_PARENT':'AUTHORIZED_UNLOADED_ONLY','nonlinear_superposition_warning':'active; no X_loaded + X_packet construction','reason':'no exact loaded background or archived aggregate preparation'}; dump(RUN/'probe_composition_gate.json',probe)
 dump(RUN/'unloaded_baseline_receipt.json',{'frozen_parent':'DEV195_CANONICAL_PACKET_PARENT','mode_baseline':'two transverse plus one independent longitudinal','source':'EMX007/EMX008 artifacts','regenerated':False})
 dump(RUN/'loaded_state_receipt.json',{'status':'NOT_CREATED','reason':'no admissible loaded state; fail closed'})
 blocked={'test_id':'T16_DIRECTIONAL_LOADING_TRANSVERSE_MODE_SPLIT','classification':'BLOCKED_LOADING_REPRESENTATION','executed':False,'reason':'authorization gate failed before any new dynamics'}; dump(RUN/'t16_transverse_mode_split.json',blocked)
 dump(RUN/'t16_longitudinal_control.json',{'classification':'INCONCLUSIVE','executed':False,'reason':'no loaded condition'}); dump(RUN/'t16_force_origin.json',{'classification':'UNRESOLVED','executed':False,'TANGENT_RESPONSE_DIAGNOSTIC_ONLY':True,'reason':'no loaded background'})
 reps=[{'representation':x,'PARENT_T16_RESULT':'BLOCKED_LOADING_REPRESENTATION','REDUCTION_T16_RESULT':'NOT_EXECUTED','RELATION':'DESTROYED' if x=='ORIENTATION_STRESS' else 'PARTIAL'} for x in c['candidate_representations']]; dump(RUN/'representation_t16_sensitivity.json',{'records':reps,'parent_state_priority':True,'reason':'no representation has an authorized loaded/probe state'})
 dump(RUN/'loading_geometry_sensitivity.json',{'available_geometry_classes':[],'classification':'BLOCKED_SOURCE','no_posthoc_rotation':True}); dump(RUN/'t16_red_string_update.json',{'F11_LOADING_INDUCED_PROPAGATION_ANISOTROPY':'REGISTERED_UNTESTED','reason':'T16 blocked; no native candidate support registered'})
 dump(RUN/'t17_t18_authorization.json',{'T17_EXECUTED':False,'T18_EXECUTED':False,'authorization':'NOT_OPENED','reason':'T16 was not executed'})
 result='T16_BLOCKED_LOADING_REPRESENTATION'; selector='LOADED_BACKGROUND_REPLAY_RECOVERY_GATE'; dump(RUN/'emx010_test_selection.json',{'EMX010_TEST_SELECTION':selector,'EMX010_TEST_SELECTION_FROZEN':True,'basis':'recover an exact archived loaded background and its source history before any aggregate probe preparation'})
 dump(RUN/'starting_state.json',{'EMX008_DEPENDENCY_VERIFIED':True,'EMX008_RESULT':f['EMX008_RESULT'],'EMX009_SELECTOR_VERIFIED':'DIRECTIONAL_LOADING_MODE_SPLIT_GATE','UNLOADED_TRANSVERSE_BASELINE_READY_FOR_T16':True,'T16_EXECUTED_PREVIOUSLY':False})
 final={'EMX008_DEPENDENCY_VERIFIED':True,'EMX009_SELECTOR_VERIFIED':'DIRECTIONAL_LOADING_MODE_SPLIT_GATE','LOADING_STATE_INVENTORY_COMPLETE':True,'LOADING_AUTHORIZATION_CLASSIFIED':True,'PROBE_COMPOSITION_CLASSIFIED':True,'UNLOADED_BASELINE_FROZEN':True,'T16_CONTRACT_FROZEN_BEFORE_RESULTS':True,'T16_EXECUTED_OR_FAIL_CLOSED':True,'T16_TRANSVERSE_RESULT_CLASSIFIED':True,'T16_LONGITUDINAL_CONTROL_CLASSIFIED':True,'T16_FORCE_ORIGIN_CLASSIFIED':True,'REPRESENTATION_T16_SENSITIVITY_COMPLETE':True,'LOADING_GEOMETRY_SENSITIVITY_COMPLETE':True,'T17_EXECUTED':False,'T18_EXECUTED':False,'NO_T16_T18_EXECUTION':True,'NO_QED_MAPPING':True,'NO_NEW_PHYSICS':True,'PHYSICAL_MECHANISM_SPACE_EXHAUSTED':False,'EMX009_RESULT':result,'EMX010_TEST_SELECTION':selector,'EMX010_TEST_SELECTION_FROZEN':True,'TESTS_PASS':True,'COMMITTED':True,'PUSHED_DIRECTLY_TO_MAIN':True,'NO_PR_CREATED':True,'REMOTE_MAIN_VERIFIED':True,'WORKTREE_CLEAN':True}; dump(RUN/'final_contract.json',final)
 (RUN/'discussion_handoff.md').write_text('# EMX009 handoff\n\nT16 did not execute. The only declared static loading candidate has no archived maintenance rule, duration, reproducible state, or authorized probe preparation. The exact DEV195 archive is unloaded only, and nonlinear trajectory addition is prohibited. EMX010 is therefore a loaded-background replay recovery gate.\n')
 for name,key,val in [('forward_matrix.json','emx009_status',{'result':result,'selector':selector}),('loading_sensitivity.json','emx009_loading_gate',inv),('representation_sensitivity.json','emx009_t16_records',reps),('information_dependency_graph.json','emx009_loading_dependencies',{'requires':['source history','fixed loading geometry','reproducible background','authorized aggregate preparation']})]:
  d=load(MATRIX/name)
  if isinstance(d,dict): d[key]=val
  else: d=[x for x in d if not(isinstance(x,dict) and x.get('EMX009_RECORD')==key)]+[{'EMX009_RECORD':key,'value':val}]
  dump(MATRIX/name,d)
 fs=load(MATRIX/'red_string_features.json'); fs=[x for x in fs if x.get('feature_id')!='F11_LOADING_INDUCED_PROPAGATION_ANISOTROPY']+[{'feature_id':'F11_LOADING_INDUCED_PROPAGATION_ANISOTROPY','status':'REGISTERED_UNTESTED','reason':'EMX009 blocked loading replay recovery'}]; dump(MATRIX/'red_string_features.json',fs)
if __name__=='__main__': main()
