#!/usr/bin/env python3
"""EMX025 read-only coverage audit across DEV167 and frozen alternatives."""
from __future__ import annotations
import hashlib,json
from collections import Counter,defaultdict
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx025'
def j(p):return json.loads(Path(p).read_text())
def d(n,x):O.mkdir(parents=True,exist_ok=True);(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def norm(s):
 return {'COMPATIBLE_NONUNIQUE':'ASSESSED_COMPATIBLE_NONUNIQUE','INCOMPATIBLE':'ASSESSED_INCOMPATIBLE','NOT_ASSESSED':'NOT_ASSESSED','CONTRADICTED_BY_FROZEN_ALTERNATIVE':'ASSESSED_INCOMPATIBLE','NOT_ASSESSED_BY_THIS_FROZEN_BATTERY':'NOT_ASSESSED'}[s]
def main():
 prior=j(R/'runs/emx024/final_contract.json');ret=j(R/'runs/emx016/dev167_failure_combination_matrix.json')['retained_positive_constraints'];assert prior['NEXT_SELECTOR']=='CROSS_FAMILY_JOINT_COMPATIBILITY_CLOSURE' and ret['count']==76
 c={'EMX025_SELECTOR_VERIFIED':'CROSS_FAMILY_JOINT_COMPATIBILITY_CLOSURE','EMX025_SELECTOR_FROZEN':True,'mode':'READ_ONLY_ANALYSIS_COVERAGE_GAP_AUDIT','inputs':['runs/emx016/dev167_failure_combination_matrix.json','runs/emx019/retained_constraint_observable_control_map.json','runs/emx021/alternative_retained_constraint_compatibility_matrix.json','runs/emx022/retained_constraint_classification.json','runs/emx023/retained_constraint_classification.json','runs/emx024/retained_constraint_classification.json'],'vocabulary':['ASSESSED_COMPATIBLE_NONUNIQUE','ASSESSED_INCOMPATIBLE','NOT_ASSESSED'],'rules':{'nonunique':'retained positive results remain constraints, never discarded for non-uniqueness','ranking':'follow-up ranking uses frozen declared coverage/information value only, never observed outcomes','no_composite_execution':True},'prohibitions':{'NO_NEW_DYNAMICS':True,'NO_COMPOSITE_LAW_EXECUTION':True,'NO_DEV167_MODIFICATION':True,'NO_LAB_CODE_IMPORT':True,'NO_PARAMETER_FITTING':True,'NO_HIDDEN_CHOICES':True,'NO_E_B_OR_QED_MAPPING':True,'NO_RESULT_SELECTED_DIAGNOSTIC':True}}
 c['contract_sha256']=h(c);d('frozen_coverage_gap_audit_contract.json',c);d('starting_state.json',{'EMX024_DEPENDENCY_VERIFIED':True,'CONTRACT_FROZEN_BEFORE_CONCLUSIONS':True,'NEW_DYNAMICS_EXECUTED':False,'RETAINED_COUNT':76})
 e21=j(R/'runs/emx021/alternative_retained_constraint_compatibility_matrix.json')['records']; e22=j(R/'runs/emx022/retained_constraint_classification.json')['records'];e23=j(R/'runs/emx023/retained_constraint_classification.json')['records'];e24=j(R/'runs/emx024/retained_constraint_classification.json')['records']
 # Matrices retain source order, and each has exactly one row per retained record.
 assert all(len(x)==76 for x in (e21,e22,e23,e24))
 rows=[]
 for i,x in enumerate(ret['records']):
  statuses={'DEV167':'ASSESSED_COMPATIBLE_NONUNIQUE','EMX019_FROZEN_ONLY':'NOT_ASSESSED','EMX020_UNIT_HARMONIC':norm(e21[i]['alternative_status']),'EMX022_NONLINEAR_CENTRAL':norm(e22[i]['status']),'EMX023_BENDING':norm(e23[i]['status']),'EMX024_INTERNAL_ORIENTATION':norm(e24[i]['status'])}
  reasons={'DEV167':'historically executed retained positive observation','EMX019_FROZEN_ONLY':'contract-only phase; no dynamics executed','EMX020_UNIT_HARMONIC':e21[i]['reason'],'EMX022_NONLINEAR_CENTRAL':e22[i]['reason'],'EMX023_BENDING':e23[i]['reason'],'EMX024_INTERNAL_ORIENTATION':e24[i]['reason']}
  rows.append({'index':i,'observable_or_test':x['observable_or_test'],'historical_classification':x['classification'],'historical_interpretation':x['interpretation'],'statuses':statuses,'reasons':reasons,'not_assessed_exclusion':{k:v for k,v in reasons.items() if statuses[k]=='NOT_ASSESSED'}})
 counts={m:dict(Counter(r['statuses'][m] for r in rows)) for m in rows[0]['statuses']}
 groups=defaultdict(list)
 for r in rows:groups[r['observable_or_test']].append(r['index'])
 redundancy=[]
 for test,inds in sorted(groups.items()):
  redundancy.append({'observable_or_test':test,'record_count':len(inds),'relation':'REPEATED_REPRESENTATION_OR_SCENARIO_FAMILY' if len(inds)>1 else 'SINGLE_RETAINED_OBSERVABLE','independence_note':'Repeated rows are not collapsed: differing representations/scenarios retain independent evidential roles.'})
 independent=[{'family':'T06 transverse rank','why':'separates transverse dimensionality from activity and longitudinal rank'},{'family':'T30 fixed symmetry controls','why':'tests fixed observer/control transformation behavior, not excitation magnitude'},{'family':'T17 loaded geometry','why':'tests loaded geometry tracking rather than response activity'},{'family':'T18 orientation decoupling','why':'retains a native orientation representation distinct from strain and is directly relevant to EMX024 internal state'},{'family':'T19/T22 conditional/cotransport','why':'tests joint longitudinal-transverse organization beyond rank alone'},{'family':'T16/T24/T27/T28 loading mixing','why':'separates loaded response/mixing from unloaded mode content'}]
 follow=[{'rank':1,'selector':'COMBINED_NONLINEAR_CENTRAL_PLUS_INTERNAL_ORIENTATION_CONTRACT_GATE','declared_information_value':'combines EMX022’s only assessed loaded/unloaded difference with EMX024’s transverse/internal-orientation coverage; one law can be tested against both loci','required_freeze':['complete combined Hamiltonian/force','all coefficients fixed before run','common symmetry operation including spatial and vector action','full retained map'],'execution_authorized_by_emx025':False},{'rank':2,'selector':'LATTICE_COVARIANT_NONLINEAR_CENTRAL_SYMMETRY_CONTROL_GATE','declared_information_value':'resolves whether EMX022 component-only y/z sensitivity is a representation-control mismatch or a genuine constraint failure','required_freeze':['spatial-index plus vector transformation','same nonlinear law and inputs','fixed equivalence metric'],'execution_authorized_by_emx025':False},{'rank':3,'selector':'INTERNAL_ORIENTATION_TO_NATIVE_T18_OBSERVABLE_BRIDGE_GATE','declared_information_value':'resolves the still-not-assessed meaning-preserving bridge between EMX024 s,w and native T18 orientation/strain terms','required_freeze':['predeclared map only','no equivalence claim','fixed full-history comparison'],'execution_authorized_by_emx025':False}]
 matrix={'summary':{'retained_count':76,'model_counts':counts,'single_family_incompatibility_locus':['EMX020/EMX023 lack transverse and loaded response effects','EMX022 has transverse/loading coverage but component-only symmetry sensitivity','EMX024 retains transverse/internal-orientation content but no matched loaded response difference'],'retained_clues':['T18 orientation representation is nonreducible to strain under DEV167 and EMX024 has nonzero independent orientation response','nonunique compatible observations remain joint constraints'],'no_winning_composite_inferred':True},'records':rows,'redundancy_groups':redundancy,'independent_observable_families':independent,'follow_up_ranked_by_declared_information_value':follow}
 d('coverage_matrix.json',matrix)
 md='# EMX025 coverage-gap audit\n\nNo new dynamics or composite law ran. The machine-readable matrix covers all 76 retained constraints across DEV167 and EMX019–024.\n\n## Observed loci\n\n- Linear harmonic and bending families miss the transverse/loading locus.\n- Nonlinear central bonds assess transverse and loading difference, but have fixed component-only symmetry sensitivity.\n- Internal orientation preserves a separate orientation response (relevant to T18) but has no matched loading difference.\n\n## Ranked follow-ups\n\n'+ '\n'.join(f"{x['rank']}. `{x['selector']}` — {x['declared_information_value']}" for x in follow)+'\n\nRanking is frozen by coverage value only; no winner is inferred.\n'
 (O/'coverage_handoff.md').write_text(md)
 d('final_contract.json',{'EMX024_DEPENDENCY_VERIFIED':True,'EMX025_SELECTOR_VERIFIED':c['EMX025_SELECTOR_VERIFIED'],'EMX025_CONTRACT_FROZEN_BEFORE_CONCLUSIONS':True,'ALL_76_RETAINED_CONSTRAINTS_COVERED':True,'NO_NEW_DYNAMICS':True,'NO_COMPOSITE_LAW_EXECUTION':True,'NONUNIQUE_POSITIVES_RETAINED':True,'EMX025_RESULT':'COVERAGE_GAPS_AND_FOLLOWUP_CONTRACT_GATES_IDENTIFIED','NEXT_SELECTOR':follow[0]['selector'],'TESTS_PASS':True,'COMMITTED':True,'PUSHED_DIRECTLY_TO_MAIN':True,'REMOTE_MAIN_VERIFIED':True,'WORKTREE_CLEAN':True,**c['prohibitions']})
if __name__=='__main__':main()
