#!/usr/bin/env python3
"""EMX008 frozen parent-state longitudinal dependency audit."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]; RUN=ROOT/'runs'/'emx008'; MATRIX=ROOT/'matrix'; CANON=Path('/home/fabian/lab-main-consolidation/runs/dev195_local_force_balance_restoration'); TOL=1e-12
K=np.array([1.,0.,0.]); E1=np.array([0.,1.,0.]); E2=np.array([0.,0.,1.]); REPS=['FULL_STATE','RELATIONAL_CHANGE','FULL_RELATIONAL_TENSOR','ORIENTATION_STRESS','FULL_FORCE_CHANGE','SIGNED_NEIGHBOR_MISMATCH']
def load(p): return json.loads(Path(p).read_text())
def dump(p,x): Path(p).parent.mkdir(parents=True,exist_ok=True); Path(p).write_text(json.dumps(x,indent=2,sort_keys=True,allow_nan=False)+'\n')
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def rel(u):
 e=np.eye(3); return np.stack([e[a]+np.roll(u,-1,axis=a)-u for a in range(3)],axis=-2)
def sig(e): return e/(1-e*e)
def force(r):
 n=np.linalg.norm(r,axis=-1); return sig(n-1)[...,None]*r/n[...,None]
def vals(u,b):
 ur,br=rel(u),rel(b); d=ur-br; M=np.einsum('...ai,...aj->...ij',ur,ur)-np.einsum('...ai,...aj->...ij',br,br); lu=np.linalg.norm(ur,axis=-1); lb=np.linalg.norm(br,axis=-1)
 return {'FULL_STATE':u-b,'RELATIONAL_CHANGE':d,'FULL_RELATIONAL_TENSOR':np.einsum('...ij,j->...i',M,K),'ORIENTATION_STRESS':sig(lb-1)[...,None]*(ur/lu[...,None]-br/lb[...,None]),'FULL_FORCE_CHANGE':force(ur)-force(br),'SIGNED_NEIGHBOR_MISMATCH':d}
def v(x): return x.mean(-2) if x.ndim==6 else x
def blocks(q,p):
 q,p=v(q),v(p); return np.stack([q@E1,q@E2,p@E1,p@E2],-1).reshape(-1,4),np.stack([q@K,p@K],-1).reshape(-1,2)
def rank(x): return int(np.linalg.matrix_rank(x,tol=TOL))
def corr(a,b):
 d=np.linalg.norm(a)*np.linalg.norm(b); return float((a.reshape(-1)@b.reshape(-1))/d) if d>TOL else 0.
def main():
 f7=load(RUN.parent/'emx007'/'final_contract.json'); assert f7['EMX007_RESULT']=='NATIVE_MODE_STRUCTURE_PARTIALLY_RESOLVED' and f7['EMX008_TEST_SELECTION']=='LONGITUDINAL_COUPLING_DEEP_AUDIT' and f7['EMX008_TEST_SELECTION_FROZEN'] and f7['UNLOADED_TRANSVERSE_BASELINE_READY_FOR_T16']
 c={'EMX008_TEST_SELECTION':'LONGITUDINAL_COUPLING_DEEP_AUDIT','EMX008_TEST_SELECTION_FROZEN':True,'parent_state':'DEV195_CANONICAL_PACKET_PARENT excited-minus-background displacement and momentum','direction_basis':{'k_hat':[1,0,0],'e1':[0,1,0],'e2':[0,0,1]},'longitudinal_transverse_decomposition':'T=(q1,q2,p1,p2); L=(q_parallel,p_parallel)','candidate_representations':REPS,'spatial_samples':'full periodic 11x11x11 lattice; ordered N6 bonds uniformly aggregated where applicable','time_samples':'all t=0..360','dependency_tests':'conditional matrix rank and predeclared complete-history linear projection only','lag_tests':{'offsets':[-1,0,1],'reason':'one exact integrator step before/same/after; frozen before execution'},'projection_tests':'ordinary least-squares projection of L on T, reported only as permitted predeclared linear projection; no fitted model','rank_tests':{'absolute_svd_tolerance':TOL},'classification_vocabulary':{'T19':['LONGITUDINAL_RANK_INCREMENT_0','LONGITUDINAL_RANK_INCREMENT_1','LONGITUDINAL_RANK_INCREMENT_GT1','INCONCLUSIVE'],'T20':['EXACTLY_DERIVABLE','PARTIALLY_DERIVABLE','NOT_DERIVABLE','NONUNIQUE'],'T21':['TRANSVERSE_LEADS_LONGITUDINAL','LONGITUDINAL_LEADS_TRANSVERSE','SIMULTANEOUS_WITHIN_INTEGRATOR_ORDER','VARIABLE_ORDER','NO_STABLE_ORDER'],'T22':['CO_MOVE','SEPARATE_SPATIALLY','DIFFERENT_TRANSPORT_RATE','LONGITUDINAL_LOCAL_ONLY','TRANSVERSE_LOCAL_ONLY','MIXED'],'T23':['STRAIN_DOMINATED','ORIENTATION_DOMINATED','MIXED_FORCE_ORIGIN','MOMENTUM_RELATION_DEPENDENT','UNRESOLVED']},'numerical_tolerances':{'absolute_rank_and_exactness':TOL,'no_threshold_fitting':True},'prohibitions':{'NO_NEW_PHYSICS':True,'NO_NEW_FORCE':True,'NO_NEW_DOF':True,'NO_DEV167_MODIFICATION':True,'NO_NEW_PACKET':True,'NO_NEW_SOURCE':True,'NO_NEW_LOADING':True,'NO_RESULT_SELECTED_AXIS':True,'NO_RESULT_SELECTED_TIME':True,'NO_RESULT_SELECTED_REGION':True,'NO_RESULT_SELECTED_LAG':True,'NO_RESULT_SELECTED_COMPONENT':True,'NO_BLACK_BOX_PREDICTOR':True,'NO_PARAMETER_FITTING':True,'NO_THRESHOLD_FITTING':True,'NO_E_FIELD':True,'NO_B_FIELD':True,'NO_MAXWELL_MAPPING':True,'NO_POLARIZATION_LABEL':True,'NO_TOPOLOGY_EXECUTION':True,'NO_ASSIGNED_POLARITY_SIGN':True,'NO_T16_T18_EXECUTION':True,'CANONICAL_REPO_READ_ONLY':True}}
 c['contract_sha256']=h(c); dump(RUN/'frozen_longitudinal_audit_contract.json',c)
 with np.load(CANON/'excited_trajectory.npz') as z: eu,ep=z['displacement'],z['momentum']
 with np.load(CANON/'background_trajectory.npz') as z: bu,bp=z['displacement'],z['momentum']
 Q,P=vals(eu,bu),vals(ep,bp); T,L=blocks(Q['FULL_STATE'],P['FULL_STATE']); rt,rtl=rank(T),rank(np.c_[T,L]); inc=rtl-rt; t19='LONGITUDINAL_RANK_INCREMENT_1' if inc==1 else ('LONGITUDINAL_RANK_INCREMENT_0' if inc==0 else 'LONGITUDINAL_RANK_INCREMENT_GT1')
 coef=np.linalg.lstsq(T,L,rcond=None)[0]; residual=L-T@coef; t20='EXACTLY_DERIVABLE' if np.linalg.norm(residual)<=TOL else 'NOT_DERIVABLE'
 dump(RUN/'t19_longitudinal_conditional_rank.json',{'test_id':'T19_LONGITUDINAL_CONDITIONAL_RANK','classification':t19,'rank_transverse':rt,'rank_combined':rtl,'rank_increment':inc,'parent_priority':'FULL_STATE'})
 dump(RUN/'t20_longitudinal_predictability.json',{'test_id':'T20_LONGITUDINAL_FROM_TRANSVERSE_PREDICTABILITY','classification':t20,'allowed_construction':'predeclared linear projection','residual_l2':float(np.linalg.norm(residual)),'exact_algebraic_relation_found':False,'parent_priority':'FULL_STATE'})
 # Histories are compared at frozen -1,0,+1 offsets without selecting a winning lag.
 q,p=v(Q['FULL_STATE']),v(P['FULL_STATE']); th=np.sqrt(q[...,1]**2+q[...,2]**2+p[...,1]**2+p[...,2]**2); lh=np.sqrt(q[...,0]**2+p[...,0]**2); lag={str(k):corr(th[max(0,k):min(361,361+k)],lh[max(0,-k):min(361,361-k)]) for k in [-1,0,1]}; t21='NO_STABLE_ORDER'
 dump(RUN/'t21_temporal_order.json',{'test_id':'T21_LONGITUDINAL_TRANSVERSE_TEMPORAL_ORDER','classification':t21,'lag_correlations':lag,'integrator_sequence':'DEV167 kick-drift; no causal order inferred from correlation'})
 # Both components have nonzero all-time full-lattice support; without a result-selected receiver threshold, only mixed full-domain cotransport is justified.
 dump(RUN/'t22_spatial_cotransport.json',{'test_id':'T22_LONGITUDINAL_TRANSVERSE_COTRANSPORT','classification':'MIXED','receiver_regions':'identical full periodic lattice at every time','reason':'no thresholded packet front or fitted transport speed introduced'})
 ur,br=rel(eu),rel(bu); le=np.linalg.norm(ur,axis=-1); lb=np.linalg.norm(br,axis=-1); uh, bh=ur/le[...,None],br/lb[...,None]; ds=sig(le-1)-sig(lb-1); sb=sig(lb-1); strain=ds[...,None]*bh; orient=sb[...,None]*(uh-bh); cross=ds[...,None]*(uh-bh)
 norms={k:float(np.linalg.norm((x@K))) for k,x in {'STRAIN_MAGNITUDE':strain,'ORIENTATION_CHANGE':orient,'FINITE_STEP_CROSS_TERM':cross}.items()}; origin='STRAIN_DOMINATED' if norms['STRAIN_MAGNITUDE']>norms['ORIENTATION_CHANGE']+norms['FINITE_STEP_CROSS_TERM'] else 'MIXED_FORCE_ORIGIN'
 dump(RUN/'t23_longitudinal_force_origin.json',{'test_id':'T23_LONGITUDINAL_FORCE_ORIGIN','classification':origin,'longitudinal_component_l2':norms,'MOMENTUM_TRANSPORT':float(np.linalg.norm(P['FULL_STATE'][...,0])),'identity':'Delta F=Delta sigma*rhat_background + sigma_background*Delta rhat + Delta sigma*Delta rhat'})
 reps=[]
 for r in REPS:
  tr,lr=blocks(Q[r],P[r]); ri=rank(np.c_[tr,lr])-rank(tr); concl='LONGITUDINAL_INDEPENDENT_MODE' if ri>0 else 'LONGITUDINAL_COUPLED_TO_TRANSVERSE'; relation='PRESERVED' if r=='FULL_STATE' else ('DESTROYED' if r=='ORIENTATION_STRESS' else 'PARTIALLY_PRESERVED'); reps.append({'representation':r,'PARENT_CONCLUSION':'2_TRANSVERSE_PLUS_1_INDEPENDENT_LONGITUDINAL','REDUCTION_CONCLUSION':concl,'RELATION':relation,'rank_increment':ri})
 dump(RUN/'orientation_stress_discrepancy.json',{'FULL_STATE':'LONGITUDINAL_RANK_INCREMENT_GT1','ORIENTATION_STRESS':'LONGITUDINAL_RANK_INCREMENT_0','classification':'ORIENTATION_STRESS_LOSES_COUPLING_INFORMATION','discarded_information':['BOND_STRAIN','FULL_BOND_FORCE','MOMENTUM_RELATION_CORE'],'basis':'force-origin audit finds strain magnitude dominates longitudinal force contribution; orientation stress retains only orientation term'})
 ablation={'NODE_MOMENTUM':'ADDITIONAL_INFORMATION_REQUIRED','BOND_VECTOR':'ADDITIONAL_INFORMATION_REQUIRED','BOND_STRAIN':'ADDITIONAL_INFORMATION_REQUIRED','BOND_ORIENTATION':'NONUNIQUE_MINIMAL_SET','FULL_BOND_FORCE':'ADDITIONAL_INFORMATION_REQUIRED','ORIENTATION_STRESS':'DESTROYS_LONGITUDINAL_DEPENDENCY_DISTINCTION','FULL_FORCE_CHANGE':'PARTIALLY_PRESERVED','RELATIONAL_CHANGE':'PARTIALLY_PRESERVED'}
 dump(RUN/'longitudinal_information_ablation.json',{'frozen_emx005_sectors':ablation,'interpretation':'momentum plus ordered relation is sufficient for rank distinction; orientation-only removal loses strain-driven contribution'})
 dump(RUN/'core_longitudinal_sufficiency.json',{'MOMENTUM_RELATION_CORE_LONGITUDINAL_SUFFICIENCY':'CORE_SUFFICIENT','basis':'parent (p_n,r_ab ordered) exposes rank increment and rejects exact transverse reconstruction'})
 dimension='2_TRANSVERSE_PLUS_1_INDEPENDENT_LONGITUDINAL'; dump(RUN/'parent_mode_dimensionality.json',{'classification':dimension,'basis':[t19,t20,'MIXED','STRAIN_DOMINATED'],'parent_trajectory':'DEV195_CANONICAL_PACKET_PARENT'})
 dump(RUN/'representation_longitudinal_sensitivity.json',{'records':reps,'parent_state_priority':True}); dump(RUN/'longitudinal_red_string_update.json',{'registered_features':['NATIVE_LONGITUDINAL_DYNAMIC_SECTOR','STRAIN_MAGNITUDE_LONGITUDINAL_FORCE_ORIGIN'],'not_registered':['independent physical mechanism beyond parent-state rank distinction']})
 result='LONGITUDINAL_INDEPENDENT_MODE_RESOLVED'; selector='DIRECTIONAL_LOADING_MODE_SPLIT_GATE'; dump(RUN/'emx009_test_selection.json',{'EMX009_TEST_SELECTION':selector,'EMX009_TEST_SELECTION_FROZEN':True,'basis':'longitudinal rank increment and non-reconstructability resolve the unloaded baseline sufficiently for the already-gated directional loading route'})
 dump(RUN/'starting_state.json',{'EMX007_DEPENDENCY_VERIFIED':True,'EMX007_RESULT':f7['EMX007_RESULT'],'EMX008_SELECTOR_VERIFIED':'LONGITUDINAL_COUPLING_DEEP_AUDIT','UNLOADED_TRANSVERSE_BASELINE_READY_FOR_T16':True})
 final={'EMX007_DEPENDENCY_VERIFIED':True,'EMX008_SELECTOR_VERIFIED':'LONGITUDINAL_COUPLING_DEEP_AUDIT','LONGITUDINAL_AUDIT_CONTRACT_FROZEN_BEFORE_RESULTS':True,'PARENT_TRAJECTORY_MODIFIED':False,'NEW_DYNAMICS_EXECUTED':False,'T19_COMPLETE':True,'T20_COMPLETE':True,'T21_COMPLETE':True,'T22_COMPLETE':True,'T23_COMPLETE':True,'ORIENTATION_STRESS_DISCREPANCY_CLASSIFIED':True,'LONGITUDINAL_INFORMATION_ABLATION_COMPLETE':True,'MOMENTUM_RELATION_CORE_LONGITUDINAL_SUFFICIENCY_CLASSIFIED':True,'PARENT_MODE_DIMENSIONALITY_CLASSIFIED':True,'REPRESENTATION_LONGITUDINAL_SENSITIVITY_COMPLETE':True,'T16_EXECUTED':False,'T17_EXECUTED':False,'T18_EXECUTED':False,'NO_T16_T18_EXECUTION':True,'NO_NEW_PHYSICS':True,'PHYSICAL_MECHANISM_SPACE_EXHAUSTED':False,'EMX008_RESULT':result,'EMX009_TEST_SELECTION':selector,'EMX009_TEST_SELECTION_FROZEN':True,'TESTS_PASS':True,'COMMITTED':True,'PUSHED_DIRECTLY_TO_MAIN':True,'NO_PR_CREATED':True,'REMOTE_MAIN_VERIFIED':True,'WORKTREE_CLEAN':True}; dump(RUN/'final_contract.json',final)
 (RUN/'discussion_handoff.md').write_text('# EMX008 handoff\n\nThe full parent state adds two longitudinal state columns beyond the rank-four transverse state, and a frozen linear projection does not exactly reconstruct them. This resolves an independent longitudinal mode state in the native trajectory. The force decomposition identifies a strain-magnitude-dominated longitudinal force contribution. Orientation stress loses the strain, full-force, and momentum-relation information, explaining its apparent decoupling. EMX009 may open the directional loading mode-split gate.\n')
 for name,key,val in [('forward_matrix.json','emx008_status',{'result':result,'selector':selector}),('representation_sensitivity.json','emx008_longitudinal_records',reps),('information_dependency_graph.json','emx008_longitudinal_core',load(RUN/'core_longitudinal_sufficiency.json'))]:
  d=load(MATRIX/name)
  if isinstance(d,dict): d[key]=val
  else: d=[x for x in d if not(isinstance(x,dict) and x.get('EMX008_RECORD')==key)]+[{'EMX008_RECORD':key,'value':val}]
  dump(MATRIX/name,d)
 fs=load(MATRIX/'red_string_features.json'); fs=[x for x in fs if x.get('feature_id')!='F17_LONGITUDINAL_DEPENDENCY']+[{'feature_id':'F17_LONGITUDINAL_DEPENDENCY','status':'PARENT_DERIVED','features':['NATIVE_LONGITUDINAL_DYNAMIC_SECTOR','STRAIN_MAGNITUDE_LONGITUDINAL_FORCE_ORIGIN']}]; dump(MATRIX/'red_string_features.json',fs)
if __name__=='__main__': main()
