#!/usr/bin/env python3
from __future__ import annotations
import json,numpy as np
from pathlib import Path
from emx051_finite_closure_candidates import DT,N,STEPS,energy,evolve,force,sha,source,witness_history
R=Path(__file__).resolve().parents[1];O=R/'runs'/'emx051'
def j(n):return json.loads((O/n).read_text())
def w(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 c=j('frozen_finite_closure_candidate_contract.json');l=j('law_source_hash_ledger.json');th=c['control_thresholds'];rows=[];comparisons=[]
 em49={x['shape']:np.array(x['new_vector']) for x in json.loads((R/'runs/emx049/source_geometry_hash_ledger.json').read_text())['executed']}
 for cand in c['candidate_laws']:
  u,p,_=source('COMPACT');zero=np.zeros_like(u);zw=witness_history(zero,cand);restf=force(zero,cand);v,e,recv,uf,pf=evolve(zero,zero,zw,cand);rows += [{'candidate':cand,'stage':'source_independent','cell':'finite_rest','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if np.all(np.isfinite(restf)) else 'FAILS_POSITIVITY','value':float(np.max(abs(restf)))},{'candidate':cand,'stage':'source_independent','cell':'positive_energy','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if energy(u,p,cand)>th['positivity'] else 'FAILS_POSITIVITY','value':energy(u,p,cand)},{'candidate':cand,'stage':'source_independent','cell':'zero_source','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if np.max(abs(v))<=th['reversal'] else 'FAILS_CONSERVATION','value':v.tolist()}]
  # reversible source-free replay
  _,_,_,a,b=evolve(u.copy(),p.copy(),zw,cand);b=-b;_,_,_,a,b=evolve(a,b,zw,cand);b=-b;err=float(max(abs(a-u).max(),abs(b-p).max()));rows.append({'candidate':cand,'stage':'source_independent','cell':'forward_reverse','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if err<=th['reversal'] else 'FAILS_REVERSIBILITY','value':err})
  basew=witness_history(u,cand);vec,en,rec,_,_=evolve(u.copy(),p.copy(),basew,cand);freevec,freeen,freerec,_,_=evolve(u.copy(),p.copy(),zw,cand);drift=float((freeen.max()-freeen.min())/freeen[0]);rows.append({'candidate':cand,'stage':'source_independent','cell':'conservation_drift','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if drift<=th['conservation_relative_drift'] else 'FAILS_CONSERVATION','value':drift})
  finew=np.zeros((361,N,N,N,3));fine,_,_,_,_=evolve(u.copy(),p.copy(),finew,cand,dt=.02,steps=360);diff=float(abs(freevec-fine).max());rows.append({'candidate':cand,'stage':'source_independent','cell':'dt_half_refinement','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if diff<=th['refinement_observer'] else 'FAILS_REFINEMENT','value':diff})
  um,pm,_=source('MIRRORED');mv,_,_,_,_=evolve(um,pm,witness_history(um,cand,enabled=False),cand);pd=float(abs(freevec-mv).max());rows.append({'candidate':cand,'stage':'source_independent','cell':'parity','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if pd<=th['parity_observer'] else 'FAILS_REVERSIBILITY','value':pd});rows.append({'candidate':cand,'stage':'source_independent','cell':'spatial_transport','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if freerec.max()>th['transport_nonzero'] else 'INSUFFICIENT_TO_DISTINGUISH','value':float(freerec.max())})
  neg=-basew;nv,ne,_,_,_=evolve(u.copy(),p.copy(),neg,cand);onev,onee,_,oneu,_=evolve(u.copy(),p.copy(),basew,cand,steps=1);work=float(np.sum(basew[0]*(oneu-u)));res=float(abs((onee[-1]-onee[0])-work)/max(abs(work),1e-30));rows += [{'candidate':cand,'stage':'source_work','cell':'zero_source','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if np.max(abs(v))<=th['reversal'] else 'FAILS_VIRTUAL_WORK_ACCOUNTING'},{'candidate':cand,'stage':'source_work','cell':'source_sign','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if np.sign(ne[-1]-ne[0])!=np.sign(en[-1]-en[0]) else 'INSUFFICIENT_TO_DISTINGUISH'},{'candidate':cand,'stage':'source_work','cell':'parity','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if pd<=th['parity_observer'] else 'FAILS_VIRTUAL_WORK_ACCOUNTING'},{'candidate':cand,'stage':'source_work','cell':'normalization','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if abs(np.linalg.norm(u)-c['geometry']['artifacts'][cand]['COMPACT']['initial_l2'])<=th['normalization'] else 'FAILS_VIRTUAL_WORK_ACCOUNTING'},{'candidate':cand,'stage':'source_work','cell':'virtual_work_accounting','classification':'PASSES_FROZEN_INTERNAL_CONTROLS' if res<=th['virtual_work_relative_residual'] else 'FAILS_VIRTUAL_WORK_ACCOUNTING','value':res}]
  for s in c['staged_registry']['packet_shapes']:
   su,sp,_=source(s);sw=witness_history(su,cand);assert sha(su)==l['artifacts'][cand][s]['u_sha256'] and sha(sw)==l['artifacts'][cand][s]['source_witness_sha256'];sv,_,_,_,_=evolve(su,sp,sw,cand);matched,_,_,_,_=evolve(su,sp,witness_history(su,cand,enabled=False),cand);cl='DIFFERENTIATES_FROM_EMX049' if abs(matched-em49[s]).max()>c['observer']['tolerance'] else 'COMPATIBLE_NONUNIQUE';comparisons.append({'candidate':cand,'stage':'integrated_packet_shapes','shape':s,'source_witness_observer_vector':sv.tolist(),'matched_zero_source_observer_vector':matched.tolist(),'emx049_vector':em49[s].tolist(),'classification':cl,'observer_diagnostic_only':True,'comparison_preparation':'identical EMX049 initial packet and zero source history'})
 counts={k:sum(x['classification']==k for x in rows+comparisons) for k in c['classification_vocabulary']};w('staged_cell_results.json',{'internal_control_cells':rows,'integrated_shape_cells':comparisons});w('comparison_matrix.json',{'rows':comparisons,'scope':'matched EMX049 preparation; EMX041 observer diagnostic only'});w('provenance_assumption_statement.json',{'statement':c['provenance'],'no_physical_validity_from_pass_or_compatibility':True});w('conclusion.json',{'counts':counts,'survivors':[x for x in c['candidate_laws'] if not any(r['candidate']==x and r['classification'].startswith('FAILS_') for r in rows)],'conclusion':'Internal-control survivors are explicit hypotheses only, not derived closures or physical validation.'});w('final_contract.json',{'EMX051_RESULT':'FINITE_CLOSURE_CANDIDATE_SEARCH_COMPLETE','COUNTS':counts,'NEXT_SELECTOR':'HELD_OUT_CLOSURE_PACKAGE_DISCRIMINATOR_CONTRACT_BOUNDARY','NEXT_BOUNDARY':'Any survivor requires separately frozen held-out positivity/conservation/reversal/source-work discrimination; no historical inference is licensed.',**c['prohibitions']})
if __name__=='__main__':main()
